g_records   <- readRDS('./data/ebd_records.rds')
g_species   <- readRDS('./data/ebd_species.rds')
g_lists     <- readRDS('./data/ebd_lists.rds')
g_states    <- readRDS('./data/ebd_states.rds')
g_districts <- readRDS('./data/ebd_districts.rds')
g_filters   <- readRDS('./data/ebd_filters.rds')
# g_admin_filters <- readRDS('admin_filters.rds')
# g_admin_filters <- data.frame(lapply(g_admin_filters, as.character), stringsAsFactors=FALSE)
g_all_filters <- sort(c(g_filters$FILTER)) #, unique(g_admin_filters$Filter.Name)))
